---
abstract: 'Forwards the contents of an OTRS queue to a given email address.'
author:
  - 'Paul Waring <paul.waring@manchester.ac.uk>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OTRS-ForwardQueue
requires:
  Email::Sender::Simple: 0
  Email::Sender::Transport::SMTP: 0
  Email::Simple: 0
  Email::Simple::Creator: 0
  Moose: 0
  Template: 0
  namespace::autoclean: 0
  perl: 5.014
  strict: 0
  warnings: 0
version: 0.01
